# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/EECE351/Lab/Lab7/Lab7.srcs/sources_1/bd/fpga_hw/ip/fpga_hw_lmb_bram_0/fpga_hw_lmb_bram_0.xci
# IP: The module: 'fpga_hw_lmb_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/EECE351/Lab/Lab7/Lab7.gen/sources_1/bd/fpga_hw/ip/fpga_hw_lmb_bram_0/fpga_hw_lmb_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fpga_hw_lmb_bram_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/EECE351/Lab/Lab7/Lab7.srcs/sources_1/bd/fpga_hw/ip/fpga_hw_lmb_bram_0/fpga_hw_lmb_bram_0.xci
# IP: The module: 'fpga_hw_lmb_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/EECE351/Lab/Lab7/Lab7.gen/sources_1/bd/fpga_hw/ip/fpga_hw_lmb_bram_0/fpga_hw_lmb_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fpga_hw_lmb_bram_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
