# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/org later lol/Basys_3_Master.xdc

# Block Designs: bd/fpga_hw/fpga_hw.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_hw || ORIG_REF_NAME==fpga_hw} -quiet] -quiet

# IP: bd/fpga_hw/ip/fpga_hw_microblaze_0_0/fpga_hw_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_hw_microblaze_0_0 || ORIG_REF_NAME==fpga_hw_microblaze_0_0} -quiet] -quiet

# IP: bd/fpga_hw/ip/fpga_hw_axi_uartlite_0_0/fpga_hw_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_hw_axi_uartlite_0_0 || ORIG_REF_NAME==fpga_hw_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/fpga_hw/ip/fpga_hw_dlmb_v10_0/fpga_hw_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_hw_dlmb_v10_0 || ORIG_REF_NAME==fpga_hw_dlmb_v10_0} -quiet] -quiet

# IP: bd/fpga_hw/ip/fpga_hw_ilmb_v10_0/fpga_hw_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_hw_ilmb_v10_0 || ORIG_REF_NAME==fpga_hw_ilmb_v10_0} -quiet] -quiet

# IP: bd/fpga_hw/ip/fpga_hw_dlmb_bram_if_cntlr_0/fpga_hw_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_hw_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==fpga_hw_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/fpga_hw/ip/fpga_hw_ilmb_bram_if_cntlr_0/fpga_hw_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_hw_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==fpga_hw_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/fpga_hw/ip/fpga_hw_lmb_bram_0/fpga_hw_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_hw_lmb_bram_0 || ORIG_REF_NAME==fpga_hw_lmb_bram_0} -quiet] -quiet

# IP: bd/fpga_hw/ip/fpga_hw_mdm_1_0/fpga_hw_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_hw_mdm_1_0 || ORIG_REF_NAME==fpga_hw_mdm_1_0} -quiet] -quiet

# IP: bd/fpga_hw/ip/fpga_hw_clk_wiz_1_0/fpga_hw_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_hw_clk_wiz_1_0 || ORIG_REF_NAME==fpga_hw_clk_wiz_1_0} -quiet] -quiet

# IP: bd/fpga_hw/ip/fpga_hw_rst_clk_wiz_1_100M_0/fpga_hw_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_hw_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==fpga_hw_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/fpga_hw/ip/fpga_hw_xbar_0/fpga_hw_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_hw_xbar_0 || ORIG_REF_NAME==fpga_hw_xbar_0} -quiet] -quiet

# IP: bd/fpga_hw/ip/fpga_hw_microblaze_0_axi_periph_0/fpga_hw_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_hw_microblaze_0_axi_periph_0 || ORIG_REF_NAME==fpga_hw_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/fpga_hw/ip/fpga_hw_axi_gpio_0_0/fpga_hw_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_hw_axi_gpio_0_0 || ORIG_REF_NAME==fpga_hw_axi_gpio_0_0} -quiet] -quiet

# IP: bd/fpga_hw/ip/fpga_hw_axi_gpio_1_1/fpga_hw_axi_gpio_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_hw_axi_gpio_1_1 || ORIG_REF_NAME==fpga_hw_axi_gpio_1_1} -quiet] -quiet

# IP: bd/fpga_hw/ip/fpga_hw_axi_gpio_2_0/fpga_hw_axi_gpio_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_hw_axi_gpio_2_0 || ORIG_REF_NAME==fpga_hw_axi_gpio_2_0} -quiet] -quiet

# IP: bd/fpga_hw/ip/fpga_hw_xlslice_0_1/fpga_hw_xlslice_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_hw_xlslice_0_1 || ORIG_REF_NAME==fpga_hw_xlslice_0_1} -quiet] -quiet

# IP: bd/fpga_hw/ip/fpga_hw_xlslice_1_1/fpga_hw_xlslice_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_hw_xlslice_1_1 || ORIG_REF_NAME==fpga_hw_xlslice_1_1} -quiet] -quiet

# IP: bd/fpga_hw/ip/fpga_hw_xlconcat_0_0/fpga_hw_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_hw_xlconcat_0_0 || ORIG_REF_NAME==fpga_hw_xlconcat_0_0} -quiet] -quiet

# IP: bd/fpga_hw/ip/fpga_hw_axi_gpio_3_0/fpga_hw_axi_gpio_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_hw_axi_gpio_3_0 || ORIG_REF_NAME==fpga_hw_axi_gpio_3_0} -quiet] -quiet

# IP: bd/fpga_hw/ip/fpga_hw_xadc_wiz_0_0/fpga_hw_xadc_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_hw_xadc_wiz_0_0 || ORIG_REF_NAME==fpga_hw_xadc_wiz_0_0} -quiet] -quiet

# IP: bd/fpga_hw/ip/fpga_hw_xlslice_4_1/fpga_hw_xlslice_4_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_hw_xlslice_4_1 || ORIG_REF_NAME==fpga_hw_xlslice_4_1} -quiet] -quiet

# IP: bd/fpga_hw/ip/fpga_hw_xlslice_5_1/fpga_hw_xlslice_5_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_hw_xlslice_5_1 || ORIG_REF_NAME==fpga_hw_xlslice_5_1} -quiet] -quiet

# IP: bd/fpga_hw/ip/fpga_hw_alarm_timer_0_1/fpga_hw_alarm_timer_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_hw_alarm_timer_0_1 || ORIG_REF_NAME==fpga_hw_alarm_timer_0_1} -quiet] -quiet

# IP: bd/fpga_hw/ip/fpga_hw_xlslice_2_0/fpga_hw_xlslice_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_hw_xlslice_2_0 || ORIG_REF_NAME==fpga_hw_xlslice_2_0} -quiet] -quiet

# IP: bd/fpga_hw/ip/fpga_hw_xlslice_3_0/fpga_hw_xlslice_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_hw_xlslice_3_0 || ORIG_REF_NAME==fpga_hw_xlslice_3_0} -quiet] -quiet

# IP: bd/fpga_hw/ip/fpga_hw_xlslice_6_0/fpga_hw_xlslice_6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_hw_xlslice_6_0 || ORIG_REF_NAME==fpga_hw_xlslice_6_0} -quiet] -quiet

# IP: bd/fpga_hw/ip/fpga_hw_xlslice_7_0/fpga_hw_xlslice_7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_hw_xlslice_7_0 || ORIG_REF_NAME==fpga_hw_xlslice_7_0} -quiet] -quiet

# IP: bd/fpga_hw/ip/fpga_hw_pmod_encoder_0_0/fpga_hw_pmod_encoder_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpga_hw_pmod_encoder_0_0 || ORIG_REF_NAME==fpga_hw_pmod_encoder_0_0} -quiet] -quiet

# XDC: d:/EECE351/Lab/Lab7/Lab7.gen/sources_1/bd/fpga_hw/fpga_hw_ooc.xdc
